---
- hosts: ctr_servers
  tasks:
  - name: update Ubuntu repo index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: update Rocky repo index
    yum:
      update_cache: yes
    when: ansible_distribution == "Rocky"