# installing httpd and also enabling services
---
- hosts: ctr_servers
  tasks:
    - name: update package cache on Rocky Linux
      yum:
        update_cache: yes
      when: ansible_distribution == "Rocky"

    - name: update package cache on Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: install Apache on Ubuntu
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install httpd on Rocky Linux
      yum:
        name: 
          - httpd
        state: latest
      when: ansible_distribution == "Rocky"
    
    - name: enable Apache service on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
    
    - name: enable httpd service on Rocky Linux
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "Rocky"