---
- hosts: web_servers
  tasks:
    - name: Update repo index
      yum:
        update_cache: yes

    - name: Install httpd package
      yum:
        name: httpd
        state: latest

    - name: Start and enable httpd service
      service:
        name: httpd
        enabled: yes
        state: started

- hosts: 192.168.1.86
  tasks:
    - name: Delete a index.html file if empty
      file:
        path: /usr/share/httpd/noindex/index.html
        state: absent

    - name: Copy index.html template
      template:
        src: index.html.j2
        dest: /usr/share/httpd/noindex/index.html

- hosts: 192.168.1.87
  tasks:
    - name: Delete a index.html file if empty
      file:
        path: /usr/share/httpd/noindex/index.html
        state: absent

    - name: Copy index.html template
      template:
        src: index1.html.j2
        dest: /usr/share/httpd/noindex/index.html

- hosts: all
  tasks:
    - name: Disable Firewalled
      service:
        name: firewalld
        enabled: no
        state: stopped

- hosts: nginx_servers
  tasks:
    - name: Update repo index
      yum:
        update_cache: yes

    - name: Install nginx package
      yum:
        name: nginx
        state: latest

    - name: Start and enable nginx service
      service:
        name: nginx
        enabled: yes
        state: started

    - name: Delete a ls.conf file if present
      file:
        path: /etc/nginx/conf.d/ls.conf
        state: absent

    - name: Ensure ls.conf file exists
      file:
        path: /etc/nginx/conf.d/ls.conf
        state: touch

    - name: Add Nginx configuration block
      blockinfile:
        path: /etc/nginx/conf.d/ls.conf
        block: |
          upstream backend {
              server 192.168.1.86:80;
              server 192.168.1.87:80;
          }

          server {
              listen 80;
              server_name localhost;

              location / {
                  proxy_pass http://backend;
              }
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Ensure Nginx service is restarted
      service:
        name: nginx
        state: restarted
